rails/personal-goals-app-project/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resource :session, only: %i[new create destroy]
  resources :users, only: %i[index show new create]
  resources :goals
  resources :user_comments, only: %i[create]
  resources :goal_comments, only: %i[create]
  resources :comments, only: %i[create]

end

rails/personal-goals-app-project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails/personal-goals-app-project/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :author, class_name: 'User'

  validates :body, presence: true
end

rails/personal-goals-app-project/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable, dependent: :destroy
  end
end

rails/personal-goals-app-project/app/models/goal.rb
class Goal < ApplicationRecord
  # concern used to dry up polymorphism code
  include Commentable

  belongs_to :user

  # has_many :goal_comments
  # has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true, length: { minimum: 6 }
  validates :completed, :private, inclusion: [true, false]

  def toggle_complete
    toggle(:completed)
  end

  def toggle_private
    toggle(:private)
  end
end

rails/personal-goals-app-project/app/models/goal_comment.rb
class GoalComment < ApplicationRecord
  # belongs_to :author, class_name: 'User'
  # belongs_to :goal

  # validates :body, presence: true
end

rails/personal-goals-app-project/app/models/user.rb
class User < ApplicationRecord
  # concern used to dry up polymorphism code
  include Commentable

  validates :email, :password_digest, :session_token, presence: true
  validates :email, :password_digest, :session_token, uniqueness: true

  validates :password, length: { minimum: 6 }, allow_nil: true

  before_validation :ensure_session_token

  has_many :goals, dependent: :destroy
  # has_many :user_comments, dependent: :destroy
  # has_many :comments, as: :commentable, dependent: :destroy

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    hashed_password = BCrypt::Password.new(self.password_digest)
    hashed_password.is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(email:, password:)
    user = User.find_by(email: email)
    user&.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

rails/personal-goals-app-project/app/models/user_comment.rb
class UserComment < ApplicationRecord
  # belongs_to :author, class_name: 'User'
  # belongs_to :user

  # validates :body, presence: true
end

rails/personal-goals-app-project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  # before_action filters

  def require_current_user!
    redirect_to new_session_path unless current_user
  end

  def require_no_current_user!
    redirect_to user_path(current_user) if current_user
  end
end

rails/personal-goals-app-project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_current_user!

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      flash[:notice] = 'Comment saved!'
    else
      flash[:errors] = @comment.errors.full_messages
    end

    redirect_back fallback_location: users_path
  end

  private

  def comment_params
    params.require(:comment).permit(
      :body,
      :commentable_id,
      :commentable_type
    )
  end
end

rails/personal-goals-app-project/app/controllers/goal_comments_controller.rb
class GoalCommentsController < ApplicationController
  before_action :require_current_user!

  def create
    @comment = GoalComment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      flash[:notice] = 'Comment saved!'
    else
      flash[:errors] = @comment.errors.full_messages
    end

    redirect_back fallback_location: goals_path
  end

  private

  def comment_params
    params.require(:comment).permit(
      :body,
      :goal_id
    )
  end
end

rails/personal-goals-app-project/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_current_user!

  def index
    @goals = current_user.goals
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      flash[:notice] = 'Goal saved!'
      redirect_to goal_path(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goal_params)
      flash[:notice] = 'Goal updated!'
      redirect_to goal_path(@goal.id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    flash[:notice] = "Goal deleted!"
    redirect_to goals_url
  end

  private

  def goal_params
    params.require(:goal).permit(
      :title,
      :description,
      :completed,
      :private,
      :user_id
    )
  end
end

rails/personal-goals-app-project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_current_user!, only: %i[new create]
  before_action :require_current_user!, only: %i[index destroy]

  def new
    @user = User.new
  end

  def create
    email = user_params[:email]
    password = user_params[:password]
    @user = User.find_by_credentials(email: email, password: password)

    if @user
      login!(@user)
      redirect_to user_path(@user)
    else
      flash.now[:errors] = ['Invalid credentials']
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout!
    redirect_to new_user_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

rails/personal-goals-app-project/app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
  before_action :require_current_user!

  def create
    @comment = UserComment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      flash[:notice] = 'Comment saved!'
    else
      flash[:errors] = @comment.errors.full_messages
      head :unprocessable_entity
    end

    redirect_back fallback_location: users_path
  end

  private

  def comment_params
    params.require(:comment).permit(
      :body,
      :user_id
    )
  end
end

rails/personal-goals-app-project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_current_user!, only: %i[new create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_path(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

rails/personal-goals-app-project/app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
end

rails/personal-goals-app-project/app/views/goals/_complete_button.html.erb
<form action='<%= goal_url(goal) %>' method='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <input type='hidden' name='_method' value='PUT'>
  <input type='hidden' name='goal[completed]' value='<%= !goal.completed %>'>
  <input type='submit'
  <% if goal.completed %>
    value='Make goal in-progress'
  <% else %>
    value='Make goal complete'
  <% end %>
  id='goal_<%= goal.id %>_completed'>
</form>

rails/personal-goals-app-project/app/views/goals/_form.html.erb
<% action = (action_type == :edit) ? goal_url(goal) : goals_url %>
<% button_value = (action_type == :edit) ? 'Update goal' : 'New goal' %>

<%= render 'shared/alerts' %>

<form action='<%= action %>' method='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <% if action_type == :edit %>
    <input name='_method' type='hidden' value='PUT'>
  <% end %>

  <label>Title:
    <input type='text' value='<%= goal.title %>' name='goal[title]'>
  </label>
  <br>

  <label>Description:
    <textarea name='goal[description]'><%= goal.description %></textarea>
  </label>
  <br>

  <label>Private?
    <input type='checkbox' name='goal[private]'
      <%= "checked='true'" if goal.private %>>
  </label>
  <br>

  <label>Completed?
    <input type='checkbox' name='goal[completed]'
      <%= "checked='true'" if goal.private %>>
  </label>
  <br>

  <input type='submit' value='<%= button_value %>'>
</form>

rails/personal-goals-app-project/app/views/goals/_privacy_button.html.erb
<form action='<%= goal_url(goal) %>' method='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <input type='hidden' name='_method' value='PUT'>
  <input type='hidden' name='goal[private]' value='<%= !goal.private %>'>
  <input type='submit'
  <% if goal.private %>
  value='Make goal public'
  <% else %>
  value='Make goal private'
  <% end %>
  id='goal_<%= goal.id %>_private'>
</form>

rails/personal-goals-app-project/app/views/goals/edit.html.erb
Edit goal

<%= render 'form', goal: @goal, action_type: :edit %>

rails/personal-goals-app-project/app/views/goals/index.html.erb
<h1>Your goals</h1>
<ul>
  <% @goals.each do |goal| %>
    <%= render "shared/show_goal_basic", goal: goal %>
  <% end %>
</ul>

rails/personal-goals-app-project/app/views/goals/new.html.erb
New goal

<%= render 'form', goal: @goal, action_type: :new %>

rails/personal-goals-app-project/app/views/goals/show.html.erb
Your goal:
<%= render 'shared/show_goal_basic', goal: @goal %>
<p>Goal comments:
  <% @goal.comments.each do |comment| %>
    <b><%= comment.body %></b>
  <% end %>

  <%= render 'shared/comments_form', commentable_id: @goal.id, commentable_type: @goal.class %>
</p>

rails/personal-goals-app-project/app/views/shared/_alerts.html.erb
<ul>
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>
</ul>

<ul>
  <% flash[:errors]&.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

rails/personal-goals-app-project/app/views/shared/_comments_form.html.erb
<h3>New comment</h3>

<form action='<%= comments_path %>' method='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <input type='hidden' name="comment[commentable_id]" value='<%= commentable_id %>'>
  <input type='hidden' name="comment[commentable_type]" value='<%= commentable_type %>'>
  <label>Comment
    <textarea name='comment[body]'></textarea>
  </label>
  <input type='submit' value='Save comment'>
</form>

rails/personal-goals-app-project/app/views/shared/_show_goal_basic.erb
<% author_logged_in = (current_user == goal.user) %>

<ul>
  <li>Owner: <%= goal.user.email %></li>
  <li>Title: <%= goal.title %></li>
  <li>Description: <%= goal.description %></li>
  <li>Goal privacy: <%= goal.private? ? 'Private' : 'Public' %>
    <%= render 'goals/privacy_button', goal: goal if author_logged_in %>
  </li>
  <li>Goal completedness: <%= goal.completed? ? 'Completed' : 'In progress' %>
    <%= render 'goals/complete_button', goal: goal if author_logged_in %>
  </li>
</ul>
<p>
  <form action='<%= goal_path(goal) %>' method='POST' >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
  <input name='_method' type='hidden' value='DELETE'>
  <input type='submit' value="Delete '<%= goal.title %>' goal">
</p>
<br>

rails/personal-goals-app-project/app/views/shared/_user_login.erb
<form action='<%= session_path %>' method='post' >
  <input name='authenticity_token' type='hidden' value='<%= form_authenticity_token %>' />

  <label for='user_email'>Email</label>
  <input
    type='text'
    name='user[email]'
    id='user_email'>

  <label for='user_password'>Password</label>
  <input
    type='password'
    name='user[password]'
    id='user_password'>

  <input type='submit' value='Log in'>
</form>

rails/personal-goals-app-project/app/views/shared/_user_logout.erb
<p>Welcome <%= current_user.email %></p>
<form action='<%= session_path %>' method='post' >
  <input name='authenticity_token' type='hidden' value='<%= form_authenticity_token %>'>
      <input type='hidden' value='delete' name='_method'>
      <input type='submit' value='Log out'>
</form>

rails/personal-goals-app-project/app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? :patch : :post) %>
<% button_value = (user.persisted? ? 'Edit user' : 'Create user') %>


<form action='<%= action %>' method='post' >
  <input name='authenticity_token' type='hidden' value='<%= form_authenticity_token %>' />
  <input name='_method' type='hidden' value='<%= method %>'>

  <label for='user_email'>Email</label>
  <input
    type='text'
    name='user[email]'
    id='user_email'
    value=<%= user.email %>>

  <label for='user_password'>Password</label>
  <input
    type='password'
    name='user[password]'
    id='user_password'
    value='<%= user.password_digest %>'>

  <input type='submit' value='<%= button_value %>'>
</form>

rails/personal-goals-app-project/app/views/users/index.html.erb
Users

<p>Here are all the users:</p>
<ul>
  <% @users.each do |user| %>
    <li><a href=<%= user_path(user) %>><%= user.email %></li>
  <% end %>
</ul>

rails/personal-goals-app-project/app/views/users/new.html.erb
Sign up

<%= render 'form', user: @user %>

rails/personal-goals-app-project/app/views/users/show.html.erb
Welcome <%= @user.email %>

<p>User goals:
  User goals count: <%= @user.goals.count %>
  <ul>
    <% @user.goals.each do |goal| %>
      <li><a href=<%= goal_path(goal) %>><%= goal.title %></a></li>
      Goal completedness: <%= goal.completed? ? 'Completed' : 'In progress' %>

      <%= render 'goals/complete_button', goal: goal if current_user == goal.user %>
    <% end %>
  </ul>
</p>
<p>User comments:
  <ul>
    <% @user.comments.each do |comment| %>
      <li><b><%= comment.author.email %>:</b> <%= comment.body %></li>
    <% end %>
  </ul>
  <%= render 'shared/comments_form', commentable_id: @user.id, commentable_type: @user.class %>
</p>