rails/music_app_testing_with_capybara/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sessions#new'

  resource :session, only: %i[new create destroy]
  resources :users
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: %i[index new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: :new
  resources :notes, only: %i[create destroy]
end

rails/music_app_testing_with_capybara/app/models/track.rb
class Track < ApplicationRecord
  validates :title, :ord, :band, :album, presence: true
  validates :bonus, inclusion: [true, false]
  validates :ord, numericality: { only_integer: true, greater_than: 0, less_than: 999 }, uniqueness: { scope: :album }

  belongs_to :album
  belongs_to :band

  has_many :notes, dependent: :destroy
end

rails/music_app_testing_with_capybara/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :redirect_if_not_logged_in

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])

    render :new
  end

  def create
    @track = Track.new(track_params)
    @track.band_id = Album.find(track_params[:album_id]).band_id

    if @track.save
      redirect_to track_path(@track.id)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to new_track_path
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_path(@track.id)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to edit_track_path(@track)
    end
  end

  def destroy
    @track = Track.find(params[:id])
    if @track&.destroy
      flash[:notice] = " Track \"#{@track.name}\" has been deleted"
      redirect_to albums_path
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to track_path(@track.id)
    end
  end

  private

  def track_params
    params.require(:track).permit(:title, :ord, :bonus, :lyrics, :album_id)
  end

  def redirect_if_not_logged_in
    redirect_to root_path unless logged_in?
  end
end

rails/music_app_testing_with_capybara/app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(lyrics)
    note_sign = '&#9835;'
    formatted_lyrics = ''

    lyrics.each_line do |line|
      formatted_lyrics << "#{note_sign} #{h(line)}"
    end

    "<pre>#{formatted_lyrics}</pre>".html_safe
  end
end

rails/music_app_testing_with_capybara/app/views/tracks/_form.html.erb
<% action = (track.persisted? ? track_url(track) : tracks_url) %>
<% method = (track.persisted? ? :patch : :post) %>
<% button_value = (track.persisted? ? 'Edit track' : 'Create track') %>

<form action='<%= action %>' method='post' >
  <input name='authenticity_token' type='hidden' value='<%= form_authenticity_token %>' />
  <input name='_method' type='hidden' value='<%= method %>'>

  <p>
    <label for='track_title'>Title</label>
    <input
      type='text'
      name='track[title]'
      id='track_title'
      value='<%= track.title %>'>
  </p>

  <p>
    <label for='track_album_id'>Album</label>
    <select name='track[album_id]' id='track_album_id'>
      <% Album.all.each do |album| %>
        <option
          <%= 'selected' if track.album_id == album.id %>
          value='<%= album.id %>'>
            <%= album.name %>
        </option>
      <% end %>
    >
    </select>
  </p>

  <p>
    <label for='track_lyrics' justify-content: 'center'>Lyrics</label>
    <textarea
      name='track[lyrics]'
      id='track_lyrics'
      placeholder='Enter lyrics here...'
      rows=5><%= track.lyrics %></textarea>
  </p>

  <p>
    <label for='track_ord'>Track number</label>
    <input
      type='number'
      min='1'
      max='999'
      name='track[ord]'
      id='track_ord'
      value='<%= track.ord %>'>
  </p>

  <p>
    <label for='track_bonus_t'>Bonus track</label>
    <input
      type='radio'
      name='track[bonus]'
      value='t'
      id='track_bonus_t'
      <%= 'checked' if track.bonus %>>
    <label for='track_bonus_f'>Regular track</label>
    <input
      type='radio'
      name='track[bonus]'
      value='f'
      id='track_bonus_f'
      <%= 'checked' if !track.bonus %>>
  </p>

  <input type='submit' value='<%= button_value %>'>
</form>

rails/music_app_testing_with_capybara/app/views/tracks/edit.html.erb
Welcome to Track edit page!

<%= render 'form', track: @track %>

rails/music_app_testing_with_capybara/app/views/tracks/new.html.erb
Welcome to new Track creation page!
<%= link_to 'Back', url_for(:back) %>
<br>
<br>
<%= render 'form', track: @track, album: @album %>

rails/music_app_testing_with_capybara/app/views/tracks/show.html.erb
<a href='<%= album_path(@track.album_id) %>'>Back to album profile</a>
<br>
<br>
Welcome to Track page!
<br>
<a href='<%= edit_track_path %>'>Edit track</a>
<p>Track title: <%= @track.title %></p>
<p>Album title: <%= @track.album.name %></p>
<p>Band: <%= @track.band.name %></p>
<p>Lyrics: <%= ugly_lyrics(@track.lyrics) %></p>
<p>Bonus track: <%= @track.bonus %></p>

<%= render 'notes/form', track: @track %>


<br>
<br>
<p>
  Track notes from users:
  <ul>
    <% @track.notes.each do |note| %>
      <li><%= render 'notes/note', note: note %></li>
    <% end %>
  </ul>
</p>