rails/music_app_testing_with_capybara/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sessions#new'

  resource :session, only: %i[new create destroy]
  resources :users
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: %i[index new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: :new
  resources :notes, only: %i[create destroy]
end

rails/music_app_testing_with_capybara/app/models/album.rb
class Album < ApplicationRecord
  validates :name, :year, presence: true
  validates :name, uniqueness: { scope: :band }
  validates :year, numericality: { only_integer: true, greater_than: 1900, less_than: 9999 }
  validates :live, inclusion: [true, false]

  after_initialize :set_defaults

  belongs_to :band

  has_many :tracks, dependent: :destroy

  private

  def set_defaults
    self.live ||= false
  end
end

rails/music_app_testing_with_capybara/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :redirect_if_not_logged_in

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_path(@album.id)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_path(band_id: album_params[:band_id])
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_path(@album.id)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_album_path(@album)
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album&.destroy
      flash[:notice] = " Album \"#{@album.name}\" has been deleted"
      redirect_to bands_path
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to album_path(@album.id)
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :year, :live, :band_id)
  end

  def redirect_if_not_logged_in
    redirect_to root_path unless logged_in?
  end
end

rails/music_app_testing_with_capybara/app/helpers/albums_helper.rb
module AlbumsHelper
end

rails/music_app_testing_with_capybara/app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>
<% button_value = (album.persisted? ? 'Edit album' : 'Create album') %>


<form action='<%= action %>' method='post' >
  <input name='authenticity_token' type='hidden' value='<%= form_authenticity_token %>' />
  <input name='_method' type='hidden' value='<%= method %>'>

  <p>
    <label for='album_name'>Name</label>
    <input
      type='text'
      name='album[name]'
      id='album_name'
      value='<%= album.name %>'>
  </p>

  <p>
    <label for='album_band_id'>Band</label>
    <select name='album[band_id]' id='album_band_id'>
      <% Band.all.each do |band| %>
        <option
          <%= 'selected' if album.band_id == band.id %>
          value='<%= band.id %>'>
            <%= band.name %>
        </option>
      <% end %>
    >
    </select>
  </p>


  <p>
    <label for='album_year'>Release year</label>
    <input
      type='number'
      min='1900'
      max='9999'
      name='album[year]'
      id='album_year'
      value='<%= album.year %>'>
  </p>

  <p>
    <label for='album_live_t'>Live</label>
    <input
      type='radio'
      name='album[live]'
      value='t'
      id='album_live_t'
      <%= 'checked' if album.live %>>
    <label for='album_live_f'>Studio</label>
    <input
      type='radio'
      name='album[live]'
      value='f'
      id='album_live_f'
      <%= 'checked' if !album.live %>>
  </p>

  <input type='submit' value='<%= button_value %>'>
</form>

rails/music_app_testing_with_capybara/app/views/albums/edit.html.erb
Welcome to Album edit page!

<%= render 'form', album: @album %>

rails/music_app_testing_with_capybara/app/views/albums/new.html.erb
Welcome to new Album creation page!
<%= link_to 'Back', url_for(:back) %>
<br>
<br>
<%= render 'form', album: @album, band: @band %>

rails/music_app_testing_with_capybara/app/views/albums/show.html.erb
<a href='<%= band_path(@album.band) %>'>Back to band profile</a>
<br>
<a href='<%= edit_album_path %>'>Edit album</a>
<br>
<a href='<%= new_album_track_path(@album) %>'>Add new track</a>
<br>

<br>
Welcome to Album page!
<p>Album name: <%= @album.name %>!</p>
<p>Band: <%= @album.band.name %>!</p>
<p>Release year: <%= @album.year %>!</p>
<p>Live album: <%= @album.live %>!</p>


<br>
<p>Tracklist:</p>
<p>
  <ul>
    <% @album.tracks.each do |track| %>
      <li>
        <a href='<%= track_path(track) %>'>
          <%= track.title %>
        </a>
      </li>
    <% end %>
  </ul>
</p>